### ISSUE TITLE
window.plugins undefined with phonegap build on some android device !?

### ISSUE THREAD

**Issue by tontione** [EddyVerbruggen/Insomnia-PhoneGap-Plugin#10]
I try to use this plugin in my phonegapbuild app.
the phonegap version is 3.3.0

i added the correct line on my confix.xml : 
 <gap:plugin name="nl.x-services.plugins.insomnia" />

and this js call : 
 window.plugins.insomnia.keepAwake();

on some android devices (android 4.4.2) it works fine, but with others (android 4.3) i have an error
"window.plugins" is undefined.

What's the matter ?

**Comment by chin123** [comment]
Hi,
I have the same issue. I have tried:
<div onclick="window.plugins.insomnia.keepAwake()">keep awake</div>
and
document.addEventListener("deviceready", readytostart(), false);
function readytostart(){
window.plugins.insomnia.keepAwake();
}
Both of them dont work.

**Comment by EddyVerbruggen** [comment]
@chin123 the latter is incorrect, you need to do `document.addEventListener("deviceready", readytostart, false);` (without the `()`)

Also, please add a JavaScript catch all error handler to see if something else is causing the problem:

```js
window.onerror = function(a,b,c) {
  alert(a); // etc
}
```

**Comment by chin123** [comment]
@EddyVerbruggen I did that now:
`document.addEventListener("deviceready", gameready, false);

function gameready(){
window.onerror = function(a,b,c) {
  alert(a); // etc
alert(b);
alert(c);
}
window.plugins.insomnia.keepAwake();
}`
It doesn't work and no errors are appearing. Also, the prevent screen from sleeping permission doesnt appear when i try to install my app.

**Comment by EddyVerbruggen** [comment]
That errorhandler needs to be moved outside the `gameready` function.

Btw, which Android device/version is this?

**Comment by chin123** [comment]
I did that and it still gave no errors.This is android 5.1.1.

**Comment by chin123** [comment]
I think it is a problem with my device and lollipop.I will reboot the device and check again.

**Comment by chin123** [comment]
No,the problem still persists.

**Comment by EddyVerbruggen** [comment]
OK, I just tested on my 5.1.1 device: all is fine.

So let's see where your problem is..

You don't by any chance have the `Content-Security-Policy` metatag enable I hope, as the Cordova starter project doesn't allow inline script execution.

If not, please have a look at the Android log via `adb logcat` when device is connected to your computer. Or use the 'catlog' app (find it in Google Play). Perhaps the log will give you a good hint.

If all else fails, email me your Android project.

**Comment by chin123** [comment]
Thanks for your help.It seems the catlog app requires root. I am not doing anything big , just testing out phonegap. Can you please tell me the code which you added  so that the plugin works? If you want to, you can see my phonegap app repo with the insomnia plugin removed as of now : https://github.com/chin123/dodge-asteroids

**Comment by EddyVerbruggen** [comment]
Hmm, that repo isn't really useful with the plugin removed, is it :)

I just created a fresh project with the cordova CLI (are you using that, or build.phonegap.com)?

```
cordova create insomniatest
cd insomniatest
cordova platform add android
cordova plugin add https://github.com/EddyVerbruggen/Insomnia-PhoneGap-Plugin
cordova prepare
```
Then remove the csp metatag from index.html and add 

```js
    <script>
        document.addEventListener("deviceready", gameready, false);
        function gameready(){
            window.plugins.insomnia.keepAwake();
        }
    </script>
```

**Comment by chin123** [comment]
Sorry for not mentioning. I am using phonegap build.

**Comment by EddyVerbruggen** [comment]
Please re-enable Insomnia in your github project and let's continue the discussion over there.
