### ISSUE TITLE
is it should be rename to "cordova-plugin-insomnia" ?

### ISSUE THREAD

**Issue by bau720123** [EddyVerbruggen/Insomnia-PhoneGap-Plugin#27]
hi @EddyVerbruggen 
according to this
![default](https://cloud.githubusercontent.com/assets/5110085/12865146/aa1fd14e-ccdf-11e5-9045-06bb1319a4e2.png)
so...
is it should be rename to "cordova-plugin-insomnia" ?

**Comment by Ritzlgrmft** [comment]
I agree with @bau720123: I am using the ionic package service for building my ios app. Unfortunately, the plugin is added with the old-fashioned id `nl.x-services.plugins.insomnia` to `config.xml`. Therefore this id will be transferred by the ionic commands to `package.json`. And then the build will fail because it cannot download the plugin with the "old" id.

So for me it would be great to get the plugin with the new id.

**Comment by EddyVerbruggen** [comment]
Yep, agreed. Done!

**Comment by Ritzlgrmft** [comment]
@EddyVerbruggen Thanks for the fast reaction!
