### ISSUE TITLE
Using camera in my app lets the app sleep.

### ISSUE THREAD

**Issue by RedTint** [EddyVerbruggen/Insomnia-PhoneGap-Plugin#29]
Hi Team,

I'm not sure whether you guys also encountered this but using camera on my phone (inside the app) to upload an image freshly taken from cam makes the app sleep even when `.keepAwake()` is called.

Thanks!

**Comment by EddyVerbruggen** [comment]
Hey, the team here :)

I'm guessing the Android activity gets recreated after the camera was used. Interesting find.

**Comment by RedTint** [comment]
Hi there,

This is actually from `ios`.

**Comment by EddyVerbruggen** [comment]
Ah, ok - [this SO issue](http://stackoverflow.com/questions/23391564/ios-idletimerdisabled-yes-works-only-until-imagepicker-was-used) describes the problem perfectly; the Camera is likely kept awake by iOS and it sets your app to 'allowed to sleep' afterwards. This should be handled better by Apple, but it is what it is.

Since I can't (and won't) hijack the camera picker delegate and re-apply Insomnia you should manually do this in your app: once the camera callback gives control back to your app invoke the plugin again.

Thanks for reposting this quirk! I'm updating the README accordingly.

**Comment by RedTint** [comment]
You're welcome. And thanks for solidifying my theory of what could be happening. :)
